### ISSUE TITLE
SKS Admin Commands

### ISSUE THREAD

**Issue by riatorz** [bilkodtop/btu-sks-telegram-bot#10]
The person (admin) whose telegram id is given to the program must be able to use some commands and these need to be developed. Sample commands is below.
- /duyurular -> All announcements added to the database should be shared with admin.
- /duyuru_ekle -> Admins can be add a new announcement. !The announcement adding format will be shared.!
- /duyuru [duyuru_id] -> The user sends a request to re-share the announcement registered in the system.

**Comment by adraarda23** [comment]
/duyurular , /duyuru command added but not tested
