### ISSUE TITLE
Daily Menu Control

### ISSUE THREAD

**Issue by riatorz** [bilkodtop/btu-sks-telegram-bot#7]
Changes made in the menu should be automatically loaded into the application. This ensures faster and seamless reflection of menu updates. 
** We need to add the functionality to check the menu daily. This is necessary to maintain consistency and freshness in the menu.

**Comment by adraarda23** [comment]
We need a control mechanism for the fresh menu every day, so when we "kill 1" the main.py, we have to instantly restart the main.py at that moment (Some hosting services do that automatically).

**Comment by adraarda23** [comment]
Now its refresh menu daily for consistency but it requires further testing
