### ISSUE TITLE
SKS Announcement System

### ISSUE THREAD

**Issue by riatorz** [bilkodtop/btu-sks-telegram-bot#9]
In SKS Announcement system, [sksduyuru.py](https://github.com/bilkodtop/btu-sks-telegram-bot/blob/main/sksduyuru.py)
Completed scraping issues, next we are working on publishing part. The task list is below.
- [x] Create a table in sqlite.
- [x] Table columns must be id (pk), title(str), link(str), date(datetime).
- [x] Published text must be bold italic sensitive.
- [ ] Links must be embeddable in published field.

**Comment by adraarda23** [comment]
Create table in sqlite and Table columns created

**Comment by adraarda23** [comment]
Italic sensitive added in c5d8e72 and announcement table added in b3f1c0a
